plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

packageExtensions:
  styled-components@*:
    dependencies:
      react-is: '*'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
